version: '3.0'
services:
  run:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /mnt/c/Users/forma/Work_BBRMI/seq_pipeline_sandbox/muni-ss/:/sc
      - /mnt/c/Users/forma/Work_BBRMI/seq_pipeline_sandbox/seq/TRANSFER/:/TRANSFER
      - /mnt/c/Users/forma/Work_BBRMI/seq_pipeline_sandbox/seq/pseudonymization_table/:/pseudo_tables
      - /mnt/c/Users/forma/Work_BBRMI/seq_pipeline_sandbox/seq/Libraries/:/Libraries
    command: bash -c "python main.py
      -s /TRANSFER
      -d /sc/PSEUDONYMIZED
      -dn /sc/NextSeqTemp
      -t /pseudo_tables
      -l /Libraries
      -lsc /sc/Libraries"
