FROM python:3.10-slim

RUN mkdir /pseudo-app

WORKDIR /pseudo-app

RUN groupadd -g 1002 sequencers && useradd -u 1005 -g sequencers export

ADD requirements.txt .
ADD main.py .
ADD pseudonymization/ pseudonymization/
ADD tests/ tests/
ADD prod-config.cfg pseudonymization/config/config.cfg

RUN pip install -r requirements.txt

USER export
