f=$1
rm -r "${f}/Data/RTALogs"
rm -r "${f}/Data/Intensities/L001"
rm -r "${f}/Thumbnail_Images"
rm -r "${f}/Recipe"
rm "${f}/Data/Intensities/RTAConfiguration.xml"
rm "${f}/Data/Intensities/BaseCalls/SampleSheet.csv"
rm "${f}/Data/Intensities/BaseCalls/Alignment/SampleSheetUsed.csv"
rm "${f}/Data/Intensities/BaseCalls/Alignment/GenerateFASTQRunStatistics.xml"
rm "${f}/Basecalling_Netcopy_complete_Read1.txt"
rm "${f}/Basecalling_Netcopy_complete_Read2.txt"
rm "${f}/Basecalling_Netcopy_complete_Read3.txt"
rm "${f}/Basecalling_Netcopy_complete_Read4.txt"
rm "${f}/ImageAnalysis_Netcopy_complete_Read1.txt"
rm "${f}/ImageAnalysis_Netcopy_complete_Read2.txt"
rm "${f}/ImageAnalysis_Netcopy_complete_Read3.txt"
rm "${f}/ImageAnalysis_Netcopy_complete_Read4.txt"
rm "${f}/QueuedForAnalysis.txt"
rm "${f}/RTAComplete.txt"